# Generated by Django 2.1 on 2019-05-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_pending_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_events',
            name='username',
        ),
    ]
