# Generated by Django 2.1.2 on 2019-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
