# Generated by Django 2.1 on 2019-04-08 12:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donationid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('transactionid', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=10)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('requestedorganization', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('subtype', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('deliveryboyassigned', models.CharField(max_length=10)),
                ('verifierassigned', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('requesteddate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField()),
                ('img', models.ImageField(blank=True, upload_to='media/images')),
                ('requesteditem', models.CharField(max_length=10)),
                ('requestedquantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Events_Supported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('emailverified', models.BooleanField(default=False)),
                ('reports', models.PositiveIntegerField(default=0)),
                ('cridits', models.FloatField(default=0)),
                ('usertype', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Event'),
        ),
        migrations.AddField(
            model_name='donation',
            name='useremail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
