# Generated by Django 2.1 on 2019-05-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_event_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deliveryboyassigned',
        ),
    ]
