# Generated by Django 2.1 on 2019-04-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_cart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='useremail',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.Profile'),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
