# Generated by Django 2.1 on 2019-04-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_event_costperitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='itemsremaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
