# Generated by Django 2.1 on 2019-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_event_itemsremaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
